Merge 3.18.43 into fuckery
3cab355c2ff3 Linux 3.18.43
02ce1fd73386 openrisc: fix the fix of copy_from_user()
fb808fa00a2c ARM: orion: convert the irq_reg_{readl,writel} calls to the new API
db9b2a3891d5 avr32: fix 'undefined reference to `___copy_from_user'
54e7defb67e1 hexagon: Fix build failures in linux-next
f6e672ada0c9 block: Do a full clone when splitting discard bios
31714bce258a btrfs: ensure that file descriptor used with subvol ioctls is a dir
400f32af8fa6 fix fault_in_multipages_...() on architectures with no-op access_ok()
1108f7038cbb ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
8a781b2ef813 fanotify: fix list corruption in fanotify_get_response()
05eb9c077253 fsnotify: add a way to stop queueing events on group shutdown
8a66ed3130d2 autofs: use dentry flags to block walks during expire
14386af60453 autofs races
de32bc4cff47 ocfs2/dlm: fix race between convert and migration
0b5f2bd0dfa4 can: flexcan: fix resume function
869454280133 USB: change bInterval default to 10 ms
e58d9a825158 fix minor infoleak in get_user_ex()
0772cbae23ce avr32: fix copy_from_user()
c352b42eb171 microblaze: fix __get_user()
d31b0dcfb1d1 microblaze: fix copy_from_user()
ba08781d8abc m32r: fix __get_user()
f27aa24d8376 blackfin: fix copy_from_user()
9050993a5a2a sparc32: fix copy_from_user()
8bd2ef709d42 sh: fix copy_from_user()
94000fc8f4ab sh64: failing __get_user() should zero
c1c77a5f1371 score: fix copy_from_user() and friends
68f1e32cd2fc score: fix __get_user/get_user
0cdee92f5c26 s390: get_user() should zero on failure
1b228faae706 ppc32: fix copy_from_user()
6c6963274709 parisc: fix copy_from_user()
499e590cbe00 openrisc: fix copy_from_user()
8260a515dd67 mn10300: copy_from_user() should zero on access_ok() failure...
f17364dd43ea mn10300: failing __get_user() and get_user() should zero
c99e37cddc0b mips: copy_from_user() must zero the destination on access_ok() failure
09baa6b1ba17 ARC: uaccess: get_user to zero out dest in cause of fault
9a34b2a78d80 metag: copy_from_user() should zero the destination on access_ok() failure
ddc84f7b3093 ia64: copy_from_user() should zero the destination on access_ok() failure
591ca382baa0 hexagon: fix strncpy_from_user() error return
a4bc5779f6e3 frv: fix clear_user()
f13847df64d5 asm-generic: make get_user() clear the destination on errors
a0ed243c9923 asm-generic: {get,put}_user ptr argument evaluate only 1 time
93e5a11e7167 nl80211: validate number of probe response CSA counters
bc6285a72c76 MIPS: Add a missing ".set pop" in an early commit
790e65fd71e0 genirq: Provide irq_gc_{lock_irqsave,unlock_irqrestore}() helpers
b5937a545309 genirq: Generic chip: Change irq_reg_{readl,writel} arguments
751750174139 MIPS: paravirt: Fix undefined reference to smp_bootstrap
e47705fb816e crypto: arm64/aes-ctr - fix NULL dereference in tail processing
4f17ddb10568 crypto: skcipher - Fix blkcipher walk OOM crash
f5c698a84c6e USB: serial: simple: add support for another Infineon flashloader
11e9b4ed3047 asm-generic: make copy_from_user() zero the destination properly
62fc2f90511b arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
f4e1eb5d3efa kvm-arm: Unmap shadow pagetables properly
1a30ab34ce72 ALSA: timer: Fix zero-division by continue of uninitialized instance
1174014a57ed ALSA: timer: Call notifier in the same spinlock
104947141651 xhci: fix null pointer dereference in stop command timeout function
029a0cab4ef6 powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
87af205b4c7a crypto: cryptd - initialize child shash_desc on import
f6692fc52b3c ipv6: addrconf: fix dev refcont leak when DAD failed
52e5087ce97a Btrfs: remove root_log_ctx from ctx list before btrfs_sync_log returns
a55325e134ec Btrfs: add missing blk_finish_plug in btrfs_sync_log()
f5518a3e2d8c usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
fb4064af0fd3 sched/core: Fix a race between try_to_wake_up() and a woken up task
a2b268541d26 iio: accel: kxsd9: Fix scaling bug
7107bc8e091a ALSA: fireworks: accessing to user space outside spinlock
3294908b6d56 ARM: imx6: add missing BM_CLPCR_BYPASS_PMIC_READY setting for imx6sx
6000f01b3e31 ALSA: usb-audio: Add sample rate inquiry quirk for B850V3 CP2114
14e3a7860512 ALSA: timer: fix NULL pointer dereference on memory allocation failure
a987c6258df6 ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
d0a2d41031c8 ARM: kirkwood: ib62x0: fix size of u-boot environment partition
cb3662589ad9 bus: arm-ccn: Fix XP watchpoint settings bitmask
703dd66fe555 bus: arm-ccn: Do not attempt to configure XPs for cycle counter
26a0e0c21382 Revert "wext: Fix 32 bit iwpriv compatibility issue with 64 bit Kernel"
177b489883ed ARM: OMAP3: hwmod data: Add sysc information for DSI
2ee6abbd821c ovl: fix workdir creation
7cc3f9b1d845 MIPS: KVM: Check for pfn noslot case

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

Conflicts:
	drivers/usb/serial/usb-serial-simple.c
	include/linux/irq.h